function [query,index,ip,qTime,gTime,pTime,bRandom] = importfun(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [QUERY,INDEX,IP,QTIME,GTIME,PTIME,BRANDOM] = IMPORTFILE(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [QUERY,INDEX,IP,QTIME,GTIME,PTIME,BRANDOM] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [query,index,ip,qTime,gTime,pTime,bRandom] =
%   importfile('gQuery_pl1.6test.edu.cn.db.csv',1, 19920);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/04/28 21:17:38

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
query = dataArray{:, 1};
index = dataArray{:, 2};
ip = dataArray{:, 3};
qTime = dataArray{:, 4};
gTime = dataArray{:, 5};
pTime = dataArray{:, 6};
bRandom = dataArray{:, 7};

