%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/benzh/repos/CS268NetworkMeasurement/mobile/matlab/hop_stat.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/04/27 14:35:57

clear all; close all; clc;
%% Initialize variables.
filename = '/Users/benzh/repos/CS268NetworkMeasurement/mobile/matlab/hop_stat_LTE.csv';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
hop = dataArray{:, 1};
ASN = dataArray{:, 2};
ip = dataArray{:, 3};
count = dataArray{:, 4};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
save hop_stat_LTE.mat;